# Generated by Django 2.2.1 on 2020-02-01 00:31

from django.db import migrations, models
import projects.models_helper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('head_shot', models.ImageField(blank=True, upload_to='projects/authors')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_title', models.CharField(max_length=100)),
                ('entry_date', models.DateTimeField(verbose_name='date published')),
                ('entry_abstract', models.TextField(max_length=500)),
                ('entry_thumbnail', models.ImageField(blank=True, default='default.png', upload_to='projects/images')),
                ('raw_entry', models.FileField(upload_to=projects.models_helper.raw_directory_path)),
                ('html_content', models.FileField(blank=True, upload_to='')),
                ('entry_slug', models.SlugField(unique=True)),
                ('entry_authors', models.ManyToManyField(to='projects.Author')),
            ],
        ),
    ]
