# Generated by Django 2.2.1 on 2019-12-30 02:35

from django.db import migrations, models
import jv_blog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_title', models.CharField(max_length=100)),
                ('entry_date', models.DateTimeField(verbose_name='date published')),
                ('entry_thumbnail', models.ImageField(blank=True, default='default.png', upload_to='static/jv_blog/images')),
                ('raw_entry', models.FileField(upload_to=jv_blog.models.raw_directory_path)),
                ('html_content', models.FileField(blank=True, upload_to=jv_blog.models.html_directory_path)),
            ],
        ),
    ]
