# Generated by Django 2.2.1 on 2020-01-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jv_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_abstract',
            field=models.CharField(default='Default entry text', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_authors',
            field=models.ManyToManyField(blank=True, to='jv_blog.Author'),
        ),
    ]
