# Generated by Django 2.2.1 on 2020-01-15 03:52

from django.db import migrations, models
import django.db.models.deletion
import jv_blog.models


class Migration(migrations.Migration):

    dependencies = [
        ('jv_blog', '0002_auto_20200101_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='author',
            name='head_shot',
            field=models.ImageField(blank=True, upload_to='jv_blog/authors'),
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.RemoveField(
            model_name='entry',
            name='entry_authors',
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_authors',
            field=models.ForeignKey(default=jv_blog.models.default_author, on_delete=django.db.models.deletion.PROTECT, to='jv_blog.Author'),
        ),
    ]
