# Generated by Django 2.2.1 on 2020-01-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jv_blog', '0003_auto_20200114_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_slug',
            field=models.SlugField(default='Default', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_abstract',
            field=models.TextField(max_length=500),
        ),
    ]
