# Generated by Django 2.2.1 on 2020-01-19 20:58

from django.db import migrations, models
import jv_blog.models


class Migration(migrations.Migration):

    dependencies = [
        ('jv_blog', '0004_auto_20200119_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='entry_authors',
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_authors',
            field=models.ManyToManyField(default=jv_blog.models.default_author, to='jv_blog.Author'),
        ),
    ]
