# Generated by Django 2.1.15 on 2020-03-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jv_blog', '0006_auto_20200129_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='engry_show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_thumbnail',
            field=models.ImageField(blank=True, default='default.png', upload_to='jv_blog/images'),
        ),
    ]
