# Generated by Django 2.1.15 on 2020-09-01 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jv_blog', '0009_auto_20200329_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_text', models.CharField(max_length=50)),
                ('entry_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jv_blog.Entry')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='blog',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='jv_blog.Blog'),
        ),
    ]
