# Generated by Django 2.2.1 on 2020-02-12 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryShort',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('repo_name', models.CharField(max_length=100)),
                ('repo_url', models.URLField()),
                ('repo_description', models.TextField(max_length=600)),
                ('repo_description_custom', models.TextField(blank=True, max_length=1000)),
                ('repo_last_update', models.DateTimeField()),
                ('repo_show', models.BooleanField()),
                ('repo_svg', models.FileField(default='/usr/src/app/media/jv_github/images/scatter_plot-24px.svg', upload_to='jv_github/images')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('avatar_url', models.URLField()),
                ('user_url', models.URLField()),
                ('repositories_url', models.URLField()),
                ('etag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=20)),
                ('tag_repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jv_github.RepositoryShort')),
            ],
        ),
        migrations.AddField(
            model_name='repositoryshort',
            name='repo_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jv_github.User'),
        ),
    ]
