# Generated by Django 2.1.15 on 2020-03-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jv_github', '0002_auto_20200315_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryshort',
            name='repo_svg',
            field=models.FileField(default='/static-serve/jv_github\\images\\scatter_plot-24px.svg', upload_to='jv_github/images'),
        ),
    ]
