# Generated by Django 2.1.15 on 2020-03-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jv_github', '0003_auto_20200315_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryshort',
            name='repo_svg',
            field=models.SlugField(choices=[('/static-serve/jv_github/imagesadd_a_photo-24px.svg', 'Insert Photo'), ('/static-serve/jv_github/imagesinsert_photo-24px.svg', 'Add Photo'), ('/static-serve/jv_github/imagesdescription-24px.svg', 'Clipboard / Assignment'), ('/static-serve/jv_github/imagesdeck-24px.svg', 'Chairs / Deck'), ('/static-serve/jv_github/imagesassignment-24px.svg', 'Description / Paper'), ('/static-serve/jv_github/imagesemoji_objects-24px.svg', 'Light Bulb / Idea'), ('/static-serve/jv_github/imagesimage_search-24px.svg', 'Search / Image Search'), ('/static-serve/jv_github/imagesmail-24px.svg', 'Mail'), ('/static-serve/jv_github/imagesmemory-24px.svg', 'Memory / Computer Chip'), ('/static-serve/jv_github/imagesmood-24px.svg', 'Smiley Face'), ('/static-serve/jv_github/imagespie_chart-24px.svg', 'Pie Chart'), ('/static-serve/jv_github/imagesscatter_plot-24px.svg', 'Scatter Plot'), ('/static-serve/jv_github/imagesscore-24px.svg', 'Score / Line Graph'), ('/static-serve/jv_github/imagessports_golf-24px.svg', 'Golf Ball'), ('/static-serve/jv_github/imagessquare_foot-24px.svg', 'Protractor'), ('/static-serve/jv_github/imagesweekend-24px.svg', 'Couch / Sofa'), ('/static-serve/jv_github/imageslink-24px.svg', 'Link / Chainlink / hyperlink')], default='/static-serve/jv_github/imagesscatter_plot-24px.svg', max_length=255),
        ),
    ]
