# Generated by Django 2.1.15 on 2020-03-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jv_github', '0004_auto_20200315_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryshort',
            name='repo_svg',
            field=models.FilePathField(match='*.svg', path='C:\\Users\\z003vrzk\\VSCodeProjects\\webapp\\my_site\\static-serve\\jv_github\\images'),
        ),
    ]
