# Generated by Django 2.1.15 on 2020-03-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jv_github', '0005_auto_20200318_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryshort',
            name='repo_svg',
            field=models.FilePathField(path='C:\\Users\\z003vrzk\\VSCodeProjects\\webapp\\my_site\\static-serve\\jv_github\\images'),
        ),
    ]
