# Generated by Django 2.1.15 on 2020-03-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jv_github', '0006_auto_20200318_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryshort',
            name='repo_svg',
            field=models.CharField(choices=[('/static-serve/jv_github\\images\\add_a_photo-24px.svg', 'Insert Photo'), ('/static-serve/jv_github\\images\\insert_photo-24px.svg', 'Add Photo'), ('/static-serve/jv_github\\images\\description-24px.svg', 'Clipboard / Assignment'), ('/static-serve/jv_github\\images\\deck-24px.svg', 'Chairs / Deck'), ('/static-serve/jv_github\\images\\assignment-24px.svg', 'Description / Paper'), ('/static-serve/jv_github\\images\\emoji_objects-24px.svg', 'Light Bulb / Idea'), ('/static-serve/jv_github\\images\\image_search-24px.svg', 'Search / Image Search'), ('/static-serve/jv_github\\images\\mail-24px.svg', 'Mail'), ('/static-serve/jv_github\\images\\memory-24px.svg', 'Memory / Computer Chip'), ('/static-serve/jv_github\\images\\mood-24px.svg', 'Smiley Face'), ('/static-serve/jv_github\\images\\pie_chart-24px.svg', 'Pie Chart'), ('/static-serve/jv_github\\images\\scatter_plot-24px.svg', 'Scatter Plot'), ('/static-serve/jv_github\\images\\score-24px.svg', 'Score / Line Graph'), ('/static-serve/jv_github\\images\\sports_golf-24px.svg', 'Golf Ball'), ('/static-serve/jv_github\\images\\square_foot-24px.svg', 'Protractor'), ('/static-serve/jv_github\\images\\weekend-24px.svg', 'Couch / Sofa'), ('/static-serve/jv_github\\images\\link-24px.svg', 'Link / Chainlink / hyperlink')], default=('/static-serve//jv_github', '/images/scatter_plot-24px.svg'), max_length=200),
        ),
    ]
