version: '3.7'

services:
    web:
        build: 
            context: .
            dockerfile: ./docker-web/Dockerfile.azure.web
        expose:
            # Set variable in azure webapp to map WEBAPP_INTERNAL_PORT
            # To local host's external port if I want content directly served by 
            # Gunicorn
            - ${WEBAPP_INTERNAL_PORT}
            - ${WEBAPP_SSH_INTERNAL_PORT}
            - "80"
        env_file:
            - ./docker-web/web.azure.env
        ports:
            - "8001:8000"