version: '3.7'

services:
    web:
        build:
            context: .
            dockerfile: nginx-dock/Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ./docker-web/web.env
            
    postgres:
        restart: always
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            # These could be set to configure the postgres database.
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - "5432:5432"

volumes:
    postgres_data: