version: '3.7'

services:
    web:
        build: 
            context: .
            dockerfile: ./docker-web/Dockerfile.local
        command: gunicorn my_site.wsgi:application --bind 0.0.0.0:8000
        volumes:
            # Static files served here during development
            - static_volume:/home/app/web/static-serve
            # - media_volume:/home/app/web/media
        expose:
            # Dont map to external ports on host, only expose container ports
            - "8000"
        env_file:
            - ./docker-web/web.env
        hostname: jv-webapp
    
    # Production uses an azure SQL database
    # postgres:
    #     restart: always
    #     image: postgres:12-alpine
    #     volumes:
    #         - postgres_data:/var/lib/postgresql/data/
    #     env_file:
    #         # Use a file to create the production server instead
    #         - ./.env
    #     ports:
    #         - "5432:5432"

    nginx:
        restart: always
        build:
            context: .
            dockerfile: ./nginx-dock/Dockerfile
        ports:
            # Requests for HTML content through port 8001
            # Proxy pass to web gunicorn
            - 8001:80
        depends_on:
            - web
        hostname: reverse
        volumes:
            # Static files are served here during production
            - static_volume:/home/app/web/static-serve
            - media_volume:/home/app/web/media

volumes:
    postgres_data:
    static_volume:
    # media_volume: