# For use on an azure instance group
# By John Vorsten 3-9-20

version: '3.7'

services:
    web:
        build: 
            context: .
            dockerfile: ./docker-web/Dockerfile.azure.group
        volumes:
            # Static files served here during development
            - static_volume:/home/app/web/static-serve
        expose:
            # Internal port for gunicorn application server
            # Request passes from proxy server to internal port
            # Expose this on Azure also
            - ${WEBAPP_SSH_INTERNAL_PORT}
            - ${WEBAPP_INTERNAL_PORT}
        env_file:
            # Environment variables should be defined in Azure also
            - ./docker-web/web.azure.group.env
        networks:
            default:
                aliases:
                # This doesn't matter on Azure - comms through localhost
                - 'web'

    nginx:
        restart: always
        build: 
            context: .
            dockerfile: docker-nginx/Dockerfile.azure.group
        ports:
            # Proxy pass to web gunicorn
            # Expose internal ports 80, 443 on proxy server
            - ${PROXY_EXTERNAL_PORT}:80
            - ${PROXY_EXTERNAL_PORT_HTTPS}:443
        env_file:
            # Also defined in Azure
            - ./docker-nginx/nginx.azure.group.env
        volumes:
            - static_volume:/home/app/web/static-serve
        networks:
            default:
                aliases:
                - 'nginx'

networks:
    # Doesn't matter in azure
    default:
volumes:
    static_volume: