version: '3.7'

services:
    web:
        build: 
            context: .
            dockerfile: ./docker-web/Dockerfile.local.web
        volumes:
            # Static files served here during development
            - static_volume:/home/app/web/static-serve
        ports:
            - "8001:8000" # Host:Container
            - "2222:2222"
        env_file:
            - ./docker-web/web.local.env

    nginx:
        restart: always
        build: 
            context: .
            dockerfile: nginx-dock/Dockerfile.azure.web
        ports:
            # Requests for HTML content through application server port defined in .env
            # Proxy pass to web gunicorn
            - ${PROXY_EXTERNAL_PORT}:80
            - ${PROXY_EXTERNAL_PORT_HTTPS}:443
        env_file:
            - ./docker-nginx/nginx.env
        volumes:
            # - C:\Users\z003vrzk\VSCodeProjects\webapp\my_site\ssl.key:/etc/nginx/ssl.key
            # - C:\Users\z003vrzk\VSCodeProjects\webapp\my_site\ssl.crt:/etc/nginx/ssl.crt

volumes:
    static_volume: