# For use on a local machine host (Testing and polishing)
# By John Vorsten 3-15-20

version: '3.7'

services:
    web:
        build: 
            context: .
            dockerfile: ./docker-web/Dockerfile.local.group
        volumes:
            # Static files served here during development
            - static_volume:/home/app/web/static-serve
        ports:
            # - 8001:${WEBAPP_INTERNAL_PORT}
            - 9001:9001 # Supervisor http server
        expose:
            # Request passes from proxy server to internal port
            # Internal port for gunicorn application server
            - ${WEBAPP_SSH_INTERNAL_PORT}
            - ${WEBAPP_INTERNAL_PORT}
        env_file:
            
            - ./docker-web/web.local.group.env
        networks:
            default:
                aliases:
                - 'web'

    nginx:
        restart: always
        build: 
            context: .
            dockerfile: docker-nginx/Dockerfile.local.group
        ports:
            # Requests for HTML content through application server port defined in .env
            # Proxy pass to web gunicorn
            - ${PROXY_EXTERNAL_PORT}:80
            - ${PROXY_EXTERNAL_PORT_HTTPS}:443
        env_file:
            - ./docker-nginx/nginx.local.group.env
        volumes:
            - static_volume:/home/app/web/static-serve
        networks:
            default:
                aliases:
                - 'nginx'

networks:
    default:
volumes:
    static_volume: