# Generated by Django 2.1.15 on 2020-08-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20200319_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.CharField(choices=[('/media/about\\images\\○ Headshot 2 v1.jpg', 'Headshot v1'), ('/media/about\\images\\○ Headshot 2 v1 zoom.jpg', 'Headshot v1 zoom'), ('/media/about\\images\\○ Headshot 2 unfilter.jpg', 'Headshot v1 unfiltered'), ('/media/about\\images\\○ Headshot 2 unfilter sq.jpg', 'Headshot unfiltered square')], default='/media/about\\images\\○ Headshot 2 unfilter sq.jpg', max_length=200),
        ),
    ]
