# For use on a local (development) testing machine
# By john vorsten 2020-3-15

version: '3.7'

services:
    web:
        build: 
            context: ../
            dockerfile: ./docker-deploy/Dockerfile.test.web
        image: web:test
        volumes:
            # Static files served here during development
            - ../my_site/static-serve/:/home/app/web/static-serve
        ports:
            - "8002:8000" # Host:Container
        env_file:
            - ./docker-compose.test.env

    nginx:
        restart: always
        depends_on:
            - web
        build: 
            context: ../
            dockerfile: ./docker-deploy/Dockerfile.test.nginx
        image: nginx:test
        ports:
            # Requests for HTML content through application server port defined in .env
            # Proxy pass from external 
            - "8000:80" # Host:container, for HTTP
            - "8001:443" # Host:container, for HTTPS
        env_file:
            - ./docker-compose.test.env
        volumes:
            - ../my_site/media:/home/nginx/web/my-site/my_site/media
            - ../my_site/static-serve:/home/nginx/web/my-site/my_site/static-serve/